vk:
    auth-url: "https://oauth.vk.com/access_token?client_id=%s&client_secret=%s&v=%s&grant_type=client_credentials"
    client-id: "5615222"
    client-secret: "7efmDxCxjXeW9HYxMNuw"
    api:
        version: 5.53
        method-url: "https://api.vk.com/method/"
spring:
    datasource:
        sql-script-encoding: UTF-8
        platform: h2
        url: jdbc:h2:mem:vkrepost
        username: sa
        password:
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: create